### ISSUE TITLE
Map repository

### ISSUE THREAD

**Issue by Daniellop1** [matt-dray/londonmapbot#11]
Hi, I'm looking for the repository for the blog tutorial to make the map with the bot tweets but I can't find it. The blog article I'm referring to is https://www.rostrum.blog/2020/12/20/londonmapbot-leaflet/

**Comment by matt-dray** [comment]
Hi @Daniellop1

* The source code for the blog is in this GitHub repository: https://github.com/matt-dray/rostrum-blog
* The R Markdown file for that article is here: https://github.com/matt-dray/rostrum-blog/blob/master/content/post/2020-12-19-londonmapbot-leaflet.Rmd
* The HTML for that article is here: https://github.com/matt-dray/rostrum-blog/blob/master/content/post/2020-12-19-londonmapbot-leaflet.html

Let me know if that helps.
