### ISSUE TITLE
Update the R script given the release of {rtweet} v1.0

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/londonmapbot#12]
Version 1.0 of the {rtweet} package [has been released](https://ropensci.org/blog/2022/07/21/rtweet-1-0-0/). There are a few breaking changes that mean the current R script in this repo will fail when the GitHub Action is triggered (e.g. [see this failed run](https://github.com/matt-dray/londonmapbot/actions/runs/2713594799)).

The [londonmapbot R script](https://github.com/matt-dray/londonmapbot/blob/master/londonmapbot-tweet.R) now uses:

* `rtweet_bot()` instead of `create_token()`
* `fileext = ".jpeg"` in `tempfile()` (relevant for downloading MapBox images)
* the arg `media_alt_text` in `post_tweet()` (originally discussed here in #6)

I wrote about this in [a blog post](https://www.rostrum.blog/2022/07/22/mapbot-rtweet-v1/).

I [notified via Twitter](https://twitter.com/mattdray/status/1550199806789931009) the accounts in [the mapbotverse](https://twitter.com/i/lists/1492559073287581707). The updates mentioned here will only cause the GitHub Action to fail for bots that are inserting an image (`media_alt_text` is only required when you upload an image, of course, while `create_token()` is deprecated but will continue to run okay).

**Comment by jcblsn** [comment]
Thanks for the update! Just saw your blog post—super helpful!

**Comment by matt-dray** [comment]
Closing now. The bot moved long ago to Mastodon and is now retired.

**Comment by matt-dray** [comment]
Closing now. The bot moved long ago to Mastodon and is now retired.
